host=0.0.0.0
port=18080
base_url=http://127.0.0.1:18080
data_dir=./data
storage_backend=postgres
eab_mappings_file=./data/eab_mappings.csv
accounts_file=./data/acme_accounts.tsv
nonces_file=./data/nonces.txt
postgres_connection_string=host=localhost port=5432 dbname=acme user=acme password=f3ron63GL@
ca_backend=openssl

openssl_ca_name=OpenSSL-Aerovia
openssl_intermediate_dir=/Users/ayushaher/Documents/Certificates/pki/aerovia/intermediate
openssl_chain_file=/Users/ayushaher/Documents/Certificates/pki/aerovia/intermediate/certs/ca-chain.crt
openssl_valid_days=90

ejbca_base_url=https://localhost:8443
ejbca_ca_name=EJBCA-Community
ejbca_client_pkcs12_path=/path/to/superadmin.p12
ejbca_client_pkcs12_password=changeit
ejbca_insecure_skip_tls_verify=true
